# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
    database: movup_dev
    adapter: postgresql
    host: localhost
    username: sboucher
    password: 
    encoding: unicode
    pool: 5

test:
    database: movup_test
    adapter: postgresql
    host: localhost
    username: sboucher
    password: 
    encoding: unicode
    pool: 5

production:
    database: movup_dev
    adapter: postgresql
    host: localhost
    username: movup
    password: movup
    encoding: unicode
    pool: 5
